#!/bin/sh
# @name Clearbot C2-R5 (gz sim, real mech-team hull)
# @type Rover
# @class Rover

. ${R}etc/init.d/rc.rover_differential_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=water}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=clearbot_boat}

# TODO: the sydney_regatta world's wind/buoyancy/wave-publisher plugins and
# its local "coast_waves" model still live in a separate vrx_ws checkout, not
# vendored into this fork (unlike Surface/SimpleHydrodynamics, which were).
# This path is local-machine-only and will not work for anyone else cloning
# this repo until those plugins/models are vendored in properly. Harmless
# no-op for the default "water" world.
VRX_GZ_SHARE="/home/naman_clearbot/CURRENT_TASKS/SIMULATION_SETUP/vrx_ws/install/vrx_gz"
if [ -d "${VRX_GZ_SHARE}" ]; then
	export GZ_SIM_RESOURCE_PATH="${GZ_SIM_RESOURCE_PATH}:${VRX_GZ_SHARE}/share/vrx_gz/models"
	export GZ_SIM_SYSTEM_PLUGIN_PATH="${GZ_SIM_SYSTEM_PLUGIN_PATH}:${VRX_GZ_SHARE}/lib"
	export LD_LIBRARY_PATH="${VRX_GZ_SHARE}/lib:${LD_LIBRARY_PATH}"
fi

param set-default SIM_GZ_EN 1

param set-default NAV_ACC_RAD 0.5
param set-default UXRCE_DDS_AG_IP 3232235876
# Differential Parameters (ported from 50002_clearbot_vehicle)
param set-default RD_WHEEL_TRACK 0.3
param set-default RD_MAX_THR_YAW_R 0.7
param set-default RD_TRANS_DRV_TRN 0.785398
param set-default RD_TRANS_TRN_DRV 0.139626

# Rover Control Parameters
param set-default RO_ACCEL_LIM 3
param set-default RO_DECEL_LIM 4
param set-default RO_JERK_LIM 5
param set-default RO_MAX_THR_SPEED 3.8

# Rover Rate Control Parameters
param set-default RO_YAW_RATE_I 0.1
param set-default RO_YAW_RATE_P 0.1
param set-default RO_YAW_RATE_LIM 250
param set-default RO_YAW_ACCEL_LIM 600
param set-default RO_YAW_DECEL_LIM 600

# Rover Attitude Control Parameters
param set-default RO_YAW_P 2.5

# Rover Position Control Parameters
param set-default RO_SPEED_LIM 3.2
param set-default RO_SPEED_I 0.01
param set-default RO_SPEED_P 0.1

# Pure Pursuit parameters
param set-default PP_LOOKAHD_GAIN 1
param set-default PP_LOOKAHD_MAX 10
param set-default PP_LOOKAHD_MIN 1

# Actuator mapping -> gz_bridge
param set-default SIM_GZ_WH_FUNC1 101 # right thruster
param set-default SIM_GZ_WH_MIN1 0
param set-default SIM_GZ_WH_MAX1 200
param set-default SIM_GZ_WH_DIS1 100

param set-default SIM_GZ_WH_FUNC2 102 # left thruster
param set-default SIM_GZ_WH_MIN2 0
param set-default SIM_GZ_WH_MAX2 200
param set-default SIM_GZ_WH_DIS2 100
