#!/bin/sh
#
# @name Clearbot Vehicle
#
# @type Rover
# @class Rover
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.rover_differential_defaults

param set-default BAT1_N_CELLS 4
param set-default BAT1_SOURCE -1
# Set geometry & output configration
param set-default RBCLW_ADDRESS 128
param set-default RBCLW_FUNC1 101
param set-default RBCLW_FUNC2 102
param set-default RBCLW_REV 1 # reverse right wheels


param set-default NAV_ACC_RAD 0.5

# Differential Parameters
param set-default RD_WHEEL_TRACK 0.3
param set-default RD_MAX_THR_YAW_R 0.7
param set-default RD_TRANS_DRV_TRN 0.785398
param set-default RD_TRANS_TRN_DRV 0.139626

# Rover Control Parameters
param set-default RO_ACCEL_LIM 3
param set-default RO_DECEL_LIM 4
param set-default RO_JERK_LIM 5
param set-default RO_MAX_THR_SPEED 1.9

# Rover Rate Control Parameters
param set-default RO_YAW_RATE_I 0.1
param set-default RO_YAW_RATE_P 0.1
param set-default RO_YAW_RATE_LIM 250
param set-default RO_YAW_ACCEL_LIM 600
param set-default RO_YAW_DECEL_LIM 600

# Rover Attitude Control Parameters
param set-default RO_YAW_P 2.5

# Rover Position Control Parameters
param set-default RO_SPEED_LIM 1.6
param set-default RO_SPEED_I 0.01
param set-default RO_SPEED_P 0.1

# Pure Pursuit parameters
param set-default PP_LOOKAHD_GAIN 1
param set-default PP_LOOKAHD_MAX 10
param set-default PP_LOOKAHD_MIN 1

# Clearbot parameters
param set-default SER_TEL3_BAUD 1000000
param set-default UXRCE_DDS_CFG 103
param set-default NAV_RCL_ACT 0
param set-default COM_RCL_EXCEPT 4
param set-default NAV_DLL_ACT 0
param set-default PWM_MAIN_FUNC8 407
param set-default PWM_MAIN_FUNC1 102
param set-default PWM_MAIN_FUNC2 101
param set-default PWM_AUX_FUNC1 407
param set-default PWM_AUX_FUNC2 408
param set-default PWM_AUX_FUNC3 409
param set-default PWM_AUX_FUNC4 410
param set-default PWM_MAIN_MIN8 1000
param set-default PWM_MAIN_MIN1 1000
param set-default PWM_MAIN_MIN2 1000
param set-default PWM_AUX_MIN1 1000
param set-default PWM_AUX_MIN2 1000
param set-default PWM_AUX_MIN3 1000
param set-default PWM_AUX_MIN4 1000
param set-default PWM_MAIN_MAX8 2000
param set-default PWM_MAIN_MAX1 2000
param set-default PWM_MAIN_MAX2 2000
param set-default PWM_AUX_MAX1 2000
param set-default PWM_AUX_MAX2 2000
param set-default PWM_AUX_MAX3 2000
param set-default PWM_AUX_MAX4 2000
param set-default PWM_MAIN_DIS8 1500
param set-default PWM_MAIN_DIS1 1500
param set-default PWM_MAIN_DIS2 1500
param set-default PWM_AUX_DIS1 1500
param set-default PWM_AUX_DIS2 1500
param set-default PWM_AUX_DIS3 1500
param set-default PWM_AUX_DIS4 1500
param set-default UAVCAN_ENABLE 3
param set-default UAVCAN_BITRATE 250000
param set-default UAVCAN_EC_FUNC1 102
param set-default UAVCAN_EC_FUNC2 101
param set-default UAVCAN_EC_FUNC3 407
param set-default UAVCAN_LGT_ANTCL 0
param set-default UAVCAN_LGT_NAV 0
param set-default UAVCAN_LGT_STROB 0
param set-default UAVCAN_PUB_ARM 1
param set-default UAVCAN_SUB_GPS 0
param set-default UAVCAN_SUB_GPS_R 0
param set-default UAVCAN_SUB_MAG 0
param set-default RC_MAP_ARM_SW 9
param set-default RC_MAP_AUX1 7
param set-default RC_MAP_AUX2 8
param set-default RC_MAP_AUX3 5
param set-default RC_MAP_AUX4 6
param set-default RC_MAP_FLTMODE 10
